spring.application.name=xls2llm

llm.openai.url=https://api.openai.com/v1
llm.openai.key=
llm.openai.org=
llm.openai.project=

llm.openai.test.url=http://localhost:1234/v1
llm.openai.test.key=1
llm.openai.test.org=rodrigonantes
llm.openai.test.project=xls2llm

custom.valid.categories=V1,V1.1,V1.2,V2,V2.1,V3
custom.valid.codes=00,01,02,03,04,05,06,07,99

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.boot.autoconfigure.logging=INFO
